config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:new, :create, :update, :destroy]
  resources :product_categories
  resources :categories, only: [:show]
  resources :products, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :owned_products, class_name: "Product", foreign_key: "owner_id"
    has_many :reviews

    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :password, presence: true

    validates :first_name, presence: true
    validates :last_name, presence: true
    
    def full_name
        # if !self.first_name == nil && !self.last_name == nil
            self.first_name + " " + self.last_name
        # end
    end

    # deactivate account

    # how many products they have
    def number_of_products_owned
        if !self.owned_products.nil?
            self.owned_products.count
        end
    end

    # total cost
    def total_cost
        if !self.owned_products.nil?
            total_cost = 0
            self.owned_products.each do |owned_product|
                total_cost += owned_product.price
            end
            total_cost
        end
    end

    # lowest cost
    def lowest_cost
        if !self.owned_products.nil?
            lowest_cost_item = self.owned_products.min_by { |owned_product| owned_product.price }
        end
    end

    # highest cost
    def highest_cost
        if !self.owned_products.nil?
            highest_cost_item = self.owned_products.max_by { |owned_product| owned_product.price }
        end
    end

    def avg_cost
        if !self.owned_products.nil?
            average = 0
            total = 0
            self.owned_products.each do |owned_product|
                total += owned_product.price
            end
            average = total / self.owned_products.count if self.owned_products.count > 0
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :fetch_user, only: [:new, :create]
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to products_path
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end 
    end

    def edit
    end
    
    def update
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user.destroy
        redirect_to new_user_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :password, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main>
    <div class="card">
        <h1>Update User Account</h1>
        <div class="card__body">
            <%= form_for @user, controller: 'users', action: 'update' do |f| %>
                <%= f.label :first_name %>
                <%= f.text_field :first_name %><br>

                <%= f.label :last_name %>
                <%= f.text_field :last_name %><br>

                <%= f.label :username %>
                <%= f.text_field :username %><br>

                <%= f.label :password %>
                <%= f.password_field :password %><br>

                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation %><br>


                <%= f.label :bio %>
                <%= f.text_area :bio %><br>

                <%= f.submit %>
                <%= button_to "Delete User", user_path, method: :delete %>
            <% end %>
        </div>
    </div>
</main>

app/views/users/new.html.erb
<main>
    <div class="card">
        <h1>New User</h1>
        <div class="card__body">
            <%= form_for @user do |f| %>
                
                <%= f.label :first_name %>
                <%= f.text_field :first_name %>
            
                <%= f.label :last_name %>
                <%= f.text_field :last_name %>
            
                <%= f.label :username %>
                <%= f.text_field :username %>
            
                <%= f.label :password %>
                <%= f.password_field :password %>
            
                <%= f.label :bio %>
                <%= f.text_area :bio %>
                    
                <%= f.submit %>
            <% end %>
            
            <% if flash[:errors] %>
                <% flash[:errors].each do |error| %>
                    <p style="color:red"><%= error %></p>
                <% end %>
            <% end %>
        </div>
    </div>
</main>

app/views/users/show.html.erb
<div class="row">
    <div class="column">
        <h1>Hi there, <%= @user.first_name.capitalize %></h1>

        <div class="user_card">
            <img src="https://www.w3schools.com/w3images/avatar6.png" alt="Avatar" style="width:100%">
            <div class="container">
                <%= @user.full_name %>
                <div class="text">
                    <%= @user.bio %>
                </div> 
            </div>
        </div>
        <div class="text">
            <h3>Username</h1>
            <%= @user.username %>
        </div>
        <%= link_to "Edit User", edit_user_path(@user) %>
        <%= link_to "New Product", new_product_path %>
    </div>

    <div class="column">
        <main>
            <h3>Owned Products: <%= @user.number_of_products_owned %>, Total Cost: $<%= @user.total_cost %>, Average Cost: $<%= @user.avg_cost %></h3>
            <% if !@user.id == nil %>
                <%= link_to "Lowest Cost Product", product_path(@user.lowest_cost) %>
                <%= link_to "Highest Cost Product", product_path(@user.highest_cost) %>
            <% end %>
            <% @user.owned_products.each do |owned_product| %>
                <div class="card">
                    <div class="card__body">
                        <div class="half">
                            <div class="text">
                                <p class="name"><%= owned_product.name %></p>
                                <p class="price"><%= owned_product.price %></p>
                            </div>
                        </div>
                        <div class="half">
                            <div class="description">
                                <p><%= owned_product.description %></p>
                            </div>
                            <div class="view__button">
                                <%= link_to "View Full Page", product_path(owned_product) %>
                            </div>
                            
                        </div>
                    </div>
                </div>
            <% end %>
        </main>
    </div>
        
    <div class="column">
        <div class="text">
            <h3>Reviews</h3>
            <% @user.reviews.each do |review| %>
                <div>
                    Name: 
                    <%= review.product.name %><br>
                    Rating: 
                    <%= review.rating %><br>
                    Content: 
                    <%= review.content %><br>
                </div><br>
            <% end %>
            <%= link_to "Leave A Review", new_review_path %>
        </div>
    </div>
</div>