config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:new, :create, :update, :destroy]
  resources :product_categories
  resources :categories, only: [:show]
  resources :products, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories, :dependent => :destroy
    has_many :categories, through: :product_categories 
    has_many :reviews
    belongs_to :owner, class_name: "User"

    validates :name, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0}
    validates :description, presence: true, length: { minimum: 10}
    validates :owner_id, presence: true

    def categories_attributes=(category_attributes)
        category_attributes.values.each do |category_attribute|
            category = Category.find_or_create_by(category_attribute)
            self.categories << category
        end
    end

    # Total Categories of a single product
    def total_category
        self.categories.count
    end

    # average rating
    def avg_rating
        average = 0
        total = 0
        self.reviews.each do |review|
            total += review.rating
        end
        average = total / self.reviews.count
    end


    def lowest_rating
        lowest_rated_review = self.reviews.min_by { |reviews| reviews.rating }
    end

    def highest_rating
        highest_rated_review = self.reviews.max_by { |reviews| reviews.rating }
    end

    def backwards_sort
       highest_rated_review = self.reviews.sort_by { |reviews| reviews.rating }
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :current_user, only: [:index]
    # before_action :require_logged_in
    # skip_before_action :, only: [:index]

    def index
        @products = Product.all
        @category = Category.all
    end
    
    def show
    end

    def new
        @product = Product.new
        @category = Category.all
    end

    def create
        @product = Product.create(product_params)
        if @product.valid?
            redirect_to @product
        else
            flash[:errors] = @review.errors.full_messages
            redirect_to new_product_path
        end
    end

    def edit
    end
    
    def update
        @product.update(product_params)
        if @product.valid?
            redirect_to @product
        else
            flash[:errors] = @product.errors.full_messages
            redirect_to edit_product_path
        end
    end

    def destroy
        @product.destroy
        redirect_to product_path 
    end

    def add
        cart << product_params
        redirect_to products_path
    end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:name, :price, :description, :owner_id, category_ids: [], categories_attributes: [:name])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<main>
    <div class="card">
        <div class="card__body">
            <%= form_for @product do |f| %>
                <%= f.label :name %><br>
                <%= f.text_field :name %><br><br>

                <%= f.label :price %><br>
                <%= f.number_field :price, step: 0.01 %><br><br>

                <%= f.label :description %><br>
                <%= f.text_area :description %><br><br>


                <%= f.label :owner %><br>
                <%= f.collection_select :owner_id, User.all, :id, :username %><br><br>

                
                <%= f.label :category %><br>
                <%= f.collection_check_boxes :category_ids, @category, :id, :name %>

                <%= f.submit %>
            <% end %>
            <% if flash[:errors] %>
                <% flash[:errors].each do |error| %>
                    <p style="color:red"><%= error %></p>
                <% end %>
            <% end %>
        </div>
    </div>
</main>

app/views/products/edit.html.erb
<%= render 'form' %>
<%= button_to "Delete Product", product_path, method: :delete %>

app/views/products/index.html.erb
<main>
    <h1>All Products</h1>
    <ul>
        <% @products.each do |product| %>
            <div class="card">
                <div class="card__body">
                    <div class="half">
                        <div class="text">
                            <h2><%= product.name %></h3>
                            
                            <% product.product_categories.each do |product_category| %>
                                <p class="name"><%= link_to product_category.category.name, category_path(product_category.category) %></p>
                            <% end %>
                            <p class="price">$<%= product.price %></p>
                            
                        </div>
                    </div>
                    <div class="half">
                        <div class="description">
                            <p><%= product.description %></p>
                        </div>
                        <div class="view__button">
                            <%= link_to "View Full Page", product_path(product) %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </ul>
</main>

app/views/products/new.html.erb
<h1>Create a Product!</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="product-column">
    <div class="product-show">
        <h3>Product Name:
        <span id="product-name"><%= @product.name %></span></h3><br>

        <h3>Product Owner:
        <span id="product-owner"><%= link_to @product.owner.username, user_path(@product.owner) %><span></h3><br>

        <h6>Price: <span id="price"><%= @product.price %></span></h6>
        

        <h6>Category:
        <% @product.product_categories.each do |pc| %>
            <span id="product-category"><%= link_to pc.category.name, category_path(pc.category) %></span>
        <% end %></h6>

        <h6>Description:</h6>
        <span id="description"><%= @product.description %></span>
    </div>
</div>

<div class="product-column">
    <h4>Review:</h4>
    <% @product.reviews.each do |review| %>
        <div class="review">
            <%= link_to review.user.full_name, user_path(review.user) %>
            <h6 id="rating">Rating: <%= review.rating %></h6>
            <span id="content"><%= review.content %></span>
        </div>
    <% end %>
</div>